version: '3.9'
services:
  redis:
    image: redis:6.2-alpine
    restart: always
    container_name: redis
    command: redis-server --save 20 1 --loglevel warning --requirepass testdev
    ports:
      - "6379:6379"

  db:
    image: postgres:latest
    container_name: db
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - db
    env_file:
      - .env
    dns:
      - 8.8.8.8
      - 1.1.1.1
    restart: on-failure
