version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis
    env_file:
      - .env
    dns:
      - 8.8.8.8
      - 1.1.1.1

  redis:
    image: redis:6.2-alpine
    restart: always
    container_name: redis
    command: redis-server --save 20 1 --loglevel warning --requirepass testdev
    ports:
      - "6379:6379"
